### ISSUE TITLE
[Inquiry] FPU issue

### ISSUE THREAD

**Issue by KamranArain** [FreeRTOS/FreeRTOS#101]
I am using cortex m4 (stm32f303). I am trying to use FPU in it but every time it stuck in hard fault handler I even called _vPORT_ENABLE_FPU()_ in the task but it does not helped. After that also used portTASK_USES_FLOATING_POINT(); but got nothing always stuck in hardfault handler if you float.
Thanks in advance

**Comment by RichardBarry** [comment]
Grateful if you can post your question into this thread in case it is the same issue.  Please also note which compiler you are using, including the compilers version number https://forums.freertos.org/t/intermittent-cm4-fault-bus-fault-in-floating-point-app/10090
