### ISSUE TITLE
[BUG] Posix Gcc Demo Create Task Failed using cmake

### ISSUE THREAD

**Issue by Siogian** [FreeRTOS/FreeRTOS#1023]
**Describe the bug**
cmakelist.txt using heap 4 can not malloc stack.

**Comment by RichardBarry** [comment]
Did you try increasing configTOTAL_HEAP_SIZE?

**Comment by AniruddhaKanhere** [comment]
@Siogian as we have not heard back from you, we shall be closing the Issue.
Feel free to re-open this Issue or open a new one.
