### ISSUE TITLE
[DOC] Missing dependencies on Posix/Linux Simulator Demo for FreeRTOS

### ISSUE THREAD

**Issue by mkovags** [FreeRTOS/FreeRTOS#1090]
**Describe the issue**
When building the examples it was also necessary to install the following additional dependencies that were not mentioned on the documentation:

* libslirp-dev
* libglib2.0-dev

Branch: main, current commit (d1d78528) 
OS: Ubuntu 22.04 

**Reference**
https://www.freertos.org/FreeRTOS-simulator-for-Linux.html

**Comment by kar-rahul-aws** [comment]
Hi @mkovags 
Thanks for reporting the issue. We will check the documentation and update you, once the needful is done.
