### ISSUE TITLE
[Feature Request] Ability to Query Task Notification Status (pending or not)

### ISSUE THREAD

**Issue by moefear85** [FreeRTOS/FreeRTOS#1094]
**Is your feature request related to a problem? Please describe.**
I want to pass a packet to another task that is awaiting a notification and expects a pointer to the packet as the notification value. However, the source task doesn't want to go through the process of putting together the entire packet if the target task is still pending (ie hasn't processed the old packet/notification yet). In such a case blocking/waiting is not an option as the source task might be an ISR or equivalent. Moreover there is no mechanism to block the source task until the target task has processed all pending notifications.

**Describe the solution you'd like**
It would be nice to have xTaskNotifyQuery(task) that returns true or false, so that the source task only attempts to prepare the packet and notify the target task if the target task is waiting for a notification.

**Describe alternatives you've considered**
One alternative is using two-way notifications. The target task notifies the source task when it has completed. But this is cumbersome.
Another alternative is to go ahead and prepare and try to pass the packet as a notification value using xTaskNotify(...,eSetValueWithoutOverwrite,...), then check the return value. But this not only creates unnecessary overhead, there are cases where the done action cannot be undone or simply discarded.

**Comment by moninom1** [comment]
Hi @moefear85 , Thank you for the feature request. We will look into your request.
In the meantime, we're happy to review any contributions in the form of a Pull Request.

**Comment by moefear85** [comment]
would love to, 9nce i find 7kstructions. git does not have --pull-request

**Comment by moninom1** [comment]
Hi @moefear85 

You can follow the following steps to create a change and a PR : 

1: Fork the [FreeRTOS/FreeRTOS](https://github.com/FreeRTOS/FreeRTOS) repo, more details [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks).
2: Clone the forked repo locally.
3: Add changes locally and commit it your own branch e.g. query_task.
4: Push the changes to your own forked GitHub repo branch query_task.
5: Create a [pull request from forked](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) FreeRTOS branch query_task to FreeRTOS main.

Let me know if you have any further questions.

**Comment by moninom1** [comment]
Hi @moefear85 

Can you please let us know if you are working on creating the Pull Request? Or you want us to work on it. Thank you

**Comment by moefear85** [comment]
i'll check with my colleagues. ask again later

**Comment by moninom1** [comment]
Hi @moefear85 
**[xTaskNotifyAndQuery](https://www.freertos.org/xTaskNotifyAndQuery.html)** does similar to what you are looking for. 
This function combines the need to notify the task along with querying whether the target task is waiting for a notification.

If you have any specific requirement other than what xTaskNotifyAndQuery is already doing, please let us know. We will look into it. Thanks

**Comment by moninom1** [comment]
Hi @moefear85 
I am closing the issue for now with the above details. Please feel free to reopen the issue if you need any more info. Than you
