### ISSUE TITLE
[DOC] Where are the best practices？

### ISSUE THREAD

**Issue by PNP-cpp** [FreeRTOS/FreeRTOS#1126]
Where are the best practices？

**Comment by PNP-cpp** [comment]
> Could you please elaborate further? Do you mean best practices using FreeRTOS Kernel?
What tools to use for development, what tools to use for simulation, and what tools to use for debugging

**Comment by amazonKamath** [comment]
Tools to use for development - It depends and best is to opt for tools supported by your MCU vendor. 
Simulation/Emulation - https://freertos.org/emulation-simulation/
Debugging -  Suggest reading our books and manuals.  https://freertos.org/Documentation/RTOS_book.html.  You might want to read chapter 11 and 12. 
Website : [Freertos.org](https://freertos.org/index.html)
Forums: https://forums.freertos.org/
Demos: https://freertos.org/FreeRTOS-quick-start-guide.html


I am closing this issue.  You can post your questions further in our user forums  https://forums.freertos.org/ and the community will be happy to answer your questions.
