### ISSUE TITLE
[BUG] transport interface for wolfSSL

### ISSUE THREAD

**Issue by rickou** [FreeRTOS/FreeRTOS#1264]
**Describe the bug**
transport_wolfSSL.c include application include file...

it include "user_settings.h" and "demo_config.h"

in wolfSSL, the user_settings.h file is included only when WOLFSSL_USER_SETTINGS is defined

regarding demo_config.h... it has nothing to do in this file... (same for the related code) this could keep the interface as a lib without user modification in it.

am i right in my expectation ?

**Comment by aggarg** [comment]
> this could keep the interface as a lib without user modification in it.

This is not a library but an implementation of transport interface which should be used as a reference. Feel free to update this file as per your application needs.

**Comment by aggarg** [comment]
I am closing this issue. Feel free to reopen if you need anything from us.
