### ISSUE TITLE
Update CORTEX R4 demo script to support non-Windows platforms

### ISSUE THREAD

**Issue by mryall-mawson** [FreeRTOS/FreeRTOS#1272]
**Is your feature request related to a problem? Please describe.**
The Cortex R4 demo code for TMS570 and RM48 has a batch file to copy some files around. This batch file only works on Windows.

**Describe the solution you'd like**
I've converted the batch file into a shell script which will work equivalently for Linux and MacOS dev environments.

**Additional context**
I'll open a PR with this enhancement shortly for you to review.

**Comment by mryall-mawson** [comment]
PR is open: #1273 

It includes a small bug fix to the batch file as well, which was checking for a non-existent directory.

**Comment by jasonpcarroll** [comment]
Hi @mryall-mawson,
I will review your PR.
Best,
Jason Carroll

**Comment by mryall-mawson** [comment]
Thanks Jason. I have updated the PR to replace the scripts with symlinks, as suggested. This has been tested locally, and works for me with CCS12.

Once the PR is merged, we will also need to update [this section of the documentation](https://freertos.org/Documentation/02-Kernel/03-Supported-devices/04-Demos/Texas-Instruments/Free_RTOS_for_TI_RM48_and_TMS570#preparing-the-code-composer-studio-eclipse-project-directory). Where can I find the source for that?

**Comment by rawalexe** [comment]
Thank you for your contribution, @DakshitBabbar  was able to merge your PR and also update the website.  Hence we closed the issue. Please go through the changes and let us know if you have any further queries
