### ISSUE TITLE
[Inquiry] A missing error assignment in QPeek.c at the Minimal folder

### ISSUE THREAD

**Issue by kaizsv** [FreeRTOS/FreeRTOS#136]
Hello, I found that an error assignment might be missed in QPeek.c at the Minimal test folder.

https://github.com/FreeRTOS/FreeRTOS/blob/d7667a0034841f2968f9f9f805030cc608bfbce1/FreeRTOS/Demo/Common/Minimal/QPeek.c#L367

**Comment by lundinc2** [comment]
@kaizsv,

Thanks for bringing this to our attention, I will investigate this.

**Comment by lundinc2** [comment]
I have now merged the above PR, thank you again for this report.
