### ISSUE TITLE
[Devide by Zero] pollqCONSUMER_DELAY Devides by Zero when configTICK_RATE_HZ is greater than 1000

### ISSUE THREAD

**Issue by EricXiaoke** [FreeRTOS/FreeRTOS#265]
**Describe the bug**
If we want to let the configTICK_RATE_HZ is greater than 1000, pollqCONSUMER_DELAY will report Devides by Zero error.

**Target**
- Development board: WIN32-MSVC
- Instruction Set Architecture: Win32
- IDE and version: Visual Studio 2013
- Toolchain and version: Visual Studio 2013

**Host**
- Host OS: Windows 10
- Version: 18362.1016

**To Reproduce**
- Use project WIN32-MSVC and configure with configTICK_RATE_HZ as 2000
- Run on Visual Studio 2013 and could observe Error	18	error C2124: divide or mod by zero	freertos\demo\common\minimal\pollq.c	192	1	RTOSDemo

**Expected behavior**
If we config configTICK_RATE_HZ as a number greater than 1000, it should define as below in PollQ.c line 71
#define pollqCONSUMER_DELAY		( pollqPRODUCER_DELAY - ( TickType_t ) ( 20 * configTICK_RATE_HZ/ 1000 ) )

**Screenshots**
![image](https://user-images.githubusercontent.com/33096548/92998070-4f987d00-f54a-11ea-8757-c68365751819.png)
If we define as below in PollQ.c line 71
#define pollqCONSUMER_DELAY		( pollqPRODUCER_DELAY - ( TickType_t ) ( 20 / portTICK_PERIOD_MS ) )
However, portmacro.h line 66
#define portTICK_PERIOD_MS			( ( TickType_t ) 1000 / configTICK_RATE_HZ )

When configTICK_RATE_HZ is greater than 1000, portTICK_PERIOD_MS will be 0,  pollqCONSUMER_DELAY will happen 20/0.

**Additional context**
e.g. code snippet to reproduce the issue.
e.g. stack trace, memory dump, debugger log, and many etc.

**Comment by RichardBarry** [comment]
Thanks for taking the time to report this.  The file in question is not part of the kernel, but an [old] demo file, and none of the demos are designed to work with a tick frequency of >1KHz, hence I will close the bug report.
