### ISSUE TITLE
[BUG] Compilation Error with Device Defender Windows Simulator Project

### ISSUE THREAD

**Issue by vanithar75** [FreeRTOS/FreeRTOS#448]
**Describe the bug**
A concise description of what the bug is.

Compilation error "xOutput': is not a member of 'MetricsType_t". The actual definition of this type in tcp_netstat.h is "XOutput". Uppercase "X" instead of the current "x"

**Target**
- Development board:  Windows Simulator
- IDE and version: Visual Studio 2019

**Host**
- Host OS: Windows 10

**To Reproduce**
Unable to build the demo project

**Comment by lundinc2** [comment]
Hi @vanithar75,

This build error has been resolved, I will close this ticket as it is resolved. Please re-open it should you have any further issues.

Thanks,

Carl
