### ISSUE TITLE
[Inquiry]hello,I am a new hand.When I transplant free rtos 10.3.0 to risk five,I encountered some problems.

### ISSUE THREAD

**Issue by yu0802chao** [FreeRTOS/FreeRTOS#45]
We do encourage you to take a look at [FreeRTOS official site](https://www.freertos.org) for general information and [FreeRTOS forum](https://forums.freertos.org) to access our community.

If still needed, could create a general inquiry report here.

**Comment by yu0802chao** [comment]
It always stuck at tasks.c 3409 line,I do not know why it happens.Can anyone helps me?

**Comment by RichardBarry** [comment]
Answered in the forums https://forums.freertos.org/t/freertos-transport/9336
