### ISSUE TITLE
[Feature Request] Improvement to UARTCommandConsole.c

### ISSUE THREAD

**Issue by RichardBarry** [FreeRTOS/FreeRTOS#548]
**Is your feature request related to a problem? Please describe.**
[UARTCommandConsole.c](https://github.com/FreeRTOS/FreeRTOS/blob/V10.4.1/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_CLI_Demos/UARTCommandConsole.c) is a template that demonstrates how to use a UART as the IO interface for FreeRTOS+CLI.  The file has two variables with the same name.  First a file scope static intended to allow tasks other than the CLI task access the serial console.  The second is function scope variable for use in the FreeRTOS+CLI task itself.  The file scope variable is never changed from its initial value of 0, and its definition is hidden by the variable of the same name in FreeRTOS+CLI task.

**Describe the solution you'd like**

1. Remove the function scope variable so all tasks, including the FreeRTOS+CLI task, use the file scope variable.
2. Add a prototype for vOutputString

See the forum post here: https://forums.freertos.org/t/uninitialized-use-of-static-variable-in-rtosdemo-examples-uartcommandconsole-c/12181

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by archigup** [comment]
> Can I work on this?

Hey, apologies for late reply. Feel free to work on the above fix; PRs are welcome!

**Comment by dougwfoster** [comment]
I didn't see any updates for this, so I created a PR.
