### ISSUE TITLE
[Feature Request] Add a method to obtain the handle of the FreeRTOS+TCP IP task

### ISSUE THREAD

**Issue by RichardBarry** [FreeRTOS/FreeRTOS#549]
**Is your feature request related to a problem? Please describe.**
The FreeRTOS+TCP stack creates a task in which it runs the TCP/IP protocol.  A forum user needed access to the task's handle in order to place the task into the Suspended state, but currently none of the FreeRTOS+TCP API functions return the task's handle.

**Describe the solution you'd like**
Add a function that returns the handle of the task created by FreeRTOS+TCP.

**Additional context**
See the forum post https://forums.freertos.org/t/start-with-tcp-ip-task-suspended/12180

**Comment by AniruddhaKanhere** [comment]
The PR https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/222 was created and merged. Closing this issue.
