### ISSUE TITLE
[BUG] _MSC_VER limit will cause no define about snprintf in vs2013

### ISSUE THREAD

**Issue by EricXiaoke** [FreeRTOS/FreeRTOS#653]
**Describe the bug**
When load FreeRTOS_Plus_TCP_Minimal_Windows_Simulator by vs2013, it will compile failed with no snprintf define
The _MSC_VER of vs2013 is 1800, it can not define snprintf in pcap-stdinc.h line 64
#if _MSC_VER < 1500
#define snprintf _snprintf
#define vsnprintf _vsnprintf
#define strdup _strdup
#endif

**Target**
- Development board: FreeRTOS_Plus_TCP_Minimal_Windows_Simulator
- Instruction Set Architecture: FreeRTOS_Plus_TCP_Minimal_Windows_Simulator
- IDE and version: visual studio 2013
- Toolchain and version: visual studio 2013

**Host**
- Host OS: Windows10
- Version: 18363.1440

**To Reproduce**
- Use project FreeRTOS_Plus_TCP_Minimal_Windows_Simulator and configure with Platform Toolset as Visual Studio 2013 (v120)
- Run on ... and could observe ... 

**Expected behavior**
Compile successfully
![image](https://user-images.githubusercontent.com/33096548/126033753-805ee444-9a02-48e5-9f8d-ba3d74ebfa90.png)

**Screenshots**
Compile failed with no snprintf define
![image](https://user-images.githubusercontent.com/33096548/126033772-cf2bf193-3031-45d7-989e-8cc2ae49ac93.png)

**Additional context**
Suggest update the following files about _MSC_VER limit as _MSC_VER < 1900
FreeRTOS\Demo\Common\ethernet\lwip-1.4.0\ports\win32\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500
FreeRTOS-Plus\Demo\AWS\Device_Defender_Windows_Simulator\Device_Defender_Demo\FreeRTOSConfig.h
	Line 190: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\AWS\Device_Shadow_Windows_Simulator\Device_Shadow_Demo\FreeRTOSConfig.h
	Line 191: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\AWS\Jobs_Windows_Simulator\Jobs_Demo\FreeRTOSConfig.h
	Line 191: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\Common\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500
FreeRTOS-Plus\Demo\coreHTTP_Windows_Simulator\HTTP_Mutual_Auth\FreeRTOSConfig.h
	Line 192: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreHTTP_Windows_Simulator\HTTP_Plaintext\FreeRTOSConfig.h
	Line 192: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreHTTP_Windows_Simulator\HTTP_S3_Download\FreeRTOSConfig.h
	Line 192: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreHTTP_Windows_Simulator\HTTP_S3_Download_Multithreaded\FreeRTOSConfig.h
	Line 192: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreHTTP_Windows_Simulator\HTTP_S3_Upload\FreeRTOSConfig.h
	Line 192: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\Common\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Basic_TLS\FreeRTOSConfig.h
	Line 191: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Keep_Alive\FreeRTOSConfig.h
	Line 193: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Multitask\FreeRTOSConfig.h
	Line 193: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Mutual_Auth\FreeRTOSConfig.h
	Line 191: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Mutual_Auth_wolfSSL\FreeRTOSConfig.h
	Line 197: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Plain_Text\FreeRTOSConfig.h
	Line 193: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\coreMQTT_Windows_Simulator\MQTT_Serializer\FreeRTOSConfig.h
	Line 193: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\corePKCS11_MQTT_Mutual_Auth_Windows_Simulator\FreeRTOSConfig.h
	Line 191: #if ( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\corePKCS11_Windows_Simulator\FreeRTOSConfig.h
	Line 126: #if( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\FreeRTOS_Plus_TCP_Minimal_Windows_Simulator\FreeRTOSConfig.h
	Line 207: #if( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Demo\FreeRTOS_Plus_TCP_Minimal_Windows_Simulator\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500
FreeRTOS-Plus\Demo\FreeRTOS_Plus_TCP_UDP_Mode_CLI_Windows_Simulator\FreeRTOSConfig.h
	Line 206: #if( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Test\FreeRTOS-Plus-TCP\Integration\Full-TCP-Networkless\Config\FreeRTOSConfig.h
	Line 207: #if( defined( _MSC_VER ) && ( _MSC_VER <= 1600 ) && !defined( snprintf ) )
FreeRTOS-Plus\Test\FreeRTOS-Plus-TCP\Integration\Full-TCP-Networkless\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500
FreeRTOS-Plus\Test\FreeRTOS-Plus-TCP\Integration\Full-TCP-Suite\WinPCap\pcap-stdinc.h
	Line 63: #if _MSC_VER < 1500

**Comment by muneebahmed10** [comment]
Hi @EricXiaoke,

I looked at `pcap-stdinc.h` and that file isn't written by FreeRTOS, it's a copy of the one from the now-unmaintained [WinPcap](https://www.winpcap.org/devel.htm). Since we are not maintaining WinPcap, we will keep it in sync with upstream instead of making such changes to it in this repository.

Additionally, we do not test on Visual Studio version 2013 since it is quite old; we use the latest version 2019 for testing. Since the Visual Studio projects in FreeRTOS are just for demonstration purposes and not for use in production, our recommendation would be to either install the latest version of the free [Visual Studio](https://visualstudio.microsoft.com/downloads/) Community edition, or, if you need to use an older version of Visual Studio, make the required changes in the WinPcap files yourself locally.
