### ISSUE TITLE
[Feature Request] Indefinite delays

### ISSUE THREAD

**Issue by moefear85** [FreeRTOS/FreeRTOS#811]
**Is your feature request related to a problem? Please describe.**
Finite delays, even portMAX_DELAY, can be a source of subtle, hard to find bugs.

**Describe the solution you'd like**
An INDEFINITE_DELAY macro that is a special value or NaN (it could for example be the maximum possible integer value, such that portMAX_DELAY's value is decreased by 1, and the macro renamed to portMAX_FINITE_DELAY), such that any function facing this, will automatically internally check if the max delay has been reached/exceeded, and automatically then reloop/retry.

**Describe alternatives you've considered**
Currently, I must place calls to blocking functions (that I pass portMAX_DELAY as a parameter) within an empty while loop, which is error-prone due to repetition, and ugly.

**Additional context**

**Comment by paulbartell** [comment]
Thanks for the feature request. I'll bring it up with the rest of the development team.

**Comment by jefftenney** [comment]
@moefear85 if you define `INCLUDE_vTaskSuspend` to `1`, then FreeRTOS treats `portMAX_DELAY` as being infinite.

**Comment by moefear85** [comment]
thx... was this a preexisting feature? I wasn't aware of it

**Comment by jefftenney** [comment]
Yes it was preexisting.  Maybe easy to miss though!

**Comment by AniruddhaKanhere** [comment]
@moefear85, did @jefftenney's comment resolve your issue?

**Comment by moefear85** [comment]
i haven't tried it yet, i'll get around to it later. btw the point of it was that it's generally safer and avoids bugs by having an explicit portINFINITE_DELAY macro that always works as such without needing to be "turned on".
