### ISSUE TITLE
[Feature Request] Is there any plans to port XT804

### ISSUE THREAD

**Issue by wyl2008056** [FreeRTOS/FreeRTOS#815]
XT804 is a risk-v cpu arch，used in W801， w806, w800 ...

**Comment by n9wxu** [comment]
There is a lot of activity on RISC-V happening.  Currently there is not a port in the official kernel repo but there are ports of FreeRTOS on the XT804 outside of the official FreeRTOS repo's.
One example is here: [https://github.com/IOsetting/wm-sdk-w806](https://github.com/IOsetting/wm-sdk-w806)
We always welcome contributions from the community.

**Comment by wyl2008056** [comment]
> There is a lot of activity on RISC-V happening. Currently there is not a port in the official kernel repo but there are ports of FreeRTOS on the XT804 outside of the official FreeRTOS repo's. One example is here: https://github.com/IOsetting/wm-sdk-w806 We always welcome contributions from the community.

hi, n9wxu, thank you for your reply.
