### ISSUE TITLE
the memory pool can not  specify size 

### ISSUE THREAD

**Issue by Barfell** [FreeRTOS/FreeRTOS#825]
in the threadx:
tx_byte_allocate(&guix_pool, &memptr, size, TX_NO_WAIT);

in the freertos v2:
memptr =osMemoryPoolAlloc(guix_pool, 0U);

the threadx specify size, but the freertos v2 not.

**Comment by paulbartell** [comment]
@Barfell : A memory pool may not be the best choice for your use case if you need to specify a different size for each object. Using the OS heap or a separate heap for guix may be the best choice.

**Comment by Barfell** [comment]
Thanks, I will try, use freertos pvPortMalloc.
