### ISSUE TITLE
Whether it is a deviation of rule 20.2 of misra C 

### ISSUE THREAD

**Issue by Joshua1023** [FreeRTOS/FreeRTOS#827]
In `FreeRTOS/Source/include/deprecated_definitions.h`, there are several places like:

line 43:
```c
#include "..\..\Source\portable\owatcom\16bitdos\pc\portmacro.h"
```

However, according to rule 20.2 of misra C, character ` \`  shall not occur in a header file name. Is there an intended deviation in such cases?

**Comment by Skptak** [comment]
Hey,

Thanks for reaching out, this would be an intended deviation in this case. This deviation is needed for compilation on windows based systems.

**Comment by Joshua1023** [comment]
Thx for your answer. But I still have a question: even on Windows, `/` in the #include directive can still work. Is it necessary to use '\' in these #include directives?

**Comment by johnrhen** [comment]
Determining this with confidence would require checking each compiler, but it is likely true that replacing `\` with `/` would function on the platforms we support. However, we do not intend to modify the deprecated file to remove the minor deviation.
