### ISSUE TITLE
[DOC] Demo 'on-windows-using-msys2' miss miDebuggerPath setting

### ISSUE THREAD

**Issue by tiantian1645** [FreeRTOS/FreeRTOS#855]
**Describe the issue**
When debug [on-windows-using-msys2](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Posix_GCC#on-windows-using-msys2)  lost gdb path setting. And before debug shold install `make` and `gdb` , so I use `pacman -S gcc make gdb`

**Reference**
https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Posix_GCC#on-windows-using-msys2

**Browser**
- Browser: [Chrome]
- Version: [106.0.5249.103]

**Comment by archigup** [comment]
Hey thanks for reaching out, would you be able additional information?
To confirm, you are trying to run the Posix_GCC demo on Windows using msys2?
Are you having trouble running the demo, or is the demo running and using gdb is the issue?
Could you post the output you are getting?

**Comment by n9wxu** [comment]
Closing this issue after PR #859
