### ISSUE TITLE
[BUG] PKCS#11 session close failure during disconnection

### ISSUE THREAD

**Issue by KazukiMochizuki926** [FreeRTOS/FreeRTOS#877]
**Describe the bug**
It's about mbedtls_pk_pkcs11.c in the dev branch.
Since the following source code is cast with a structure suitable for ECDSA, it fails to close the PKCS#11 session when the key type is RSA.
We believe that you need to cast with a struct that matches the key you are using.
https://github.com/FreeRTOS/FreeRTOS/blob/dev/FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c#L326
![image](https://user-images.githubusercontent.com/59954281/202945160-63fa8a17-57f2-4e1f-bae6-54c09ccd9963.png)

**Target**
- Development board: CK-RX65N
- Instruction Set Architecture: Renesas RX
- IDE and version: e2 studio-2022-10
- Toolchain and version: Renesas CC-RX v3.04.00

**Host**
- Host OS: Windows
- Version: Windows 10

**To Reproduce**
- We built a project for CK-RX65N based on corePKCS11_MQTT_Mutual_Auth_Windows_Simulator.
- An error occurs within the lPKCS11PkMbedtlsCloseSessionAndFree function for closing the connection.

**Expected behavior**
PKCS#11 session close fails when key type is RSA.

**Screenshots**
![image](https://user-images.githubusercontent.com/59954281/202944246-a87f2be9-fd20-4acf-b2e9-23dd96f643d9.png)

**Comment by paulbartell** [comment]
@KazukiMochizuki926 Thanks for your report. I'll address this today.

**Comment by KazukiMochizuki926** [comment]
Thanks for the bug fix.
However, `pxMbedtlsPkCtx->pk_info.type` and `pxMbedtlsPkCtx->pk_info.type` gave a compilation error.
I believe the code below is correct.

```c
        if( pxMbedtlsPkCtx->pk_info->type == MBEDTLS_PK_ECKEY )
        {
            pxP11Ctx = &( ( ( P11EcDsaCtx_t * ) ( pxMbedtlsPkCtx->pk_ctx ) )->xP11PkCtx );
        }
        else if( pxMbedtlsPkCtx->pk_info->type == MBEDTLS_PK_RSA )
        {
            pxP11Ctx = &( ( ( P11RsaCtx_t * ) ( pxMbedtlsPkCtx->pk_ctx ) )->xP11PkCtx );
        }
        else
        {
            pxP11Ctx = NULL;
            xResult = CKR_FUNCTION_FAILED;
        }
```

**Comment by paulbartell** [comment]
@KazukiMochizuki926 Thanks much. We've integrated these changes into the dev branch.
