### ISSUE TITLE
Can FreeRTOS-Plus-TCP support multiple local Ip addresses?

### ISSUE THREAD

**Issue by 2019wang** [FreeRTOS/FreeRTOS#885]
In FreeRTOS_IP.c file, the local ip address is assigned to ipLOCAL_IP_ADDRESS_POINTER variable in the FreeRTOS_IPInit function, It looks like it can only be configured with one ip address. Is there any way to configure multiple ip addresses for different services?

**Comment by paulbartell** [comment]
@2019wang : Multiple addresses is currently not supported. I'll add it to our feature request list for prioritization.

In the mean time, if you have a near term need for it, feel free to implement it and open a PR.

**Comment by 2019wang** [comment]
Thank you for your answer
