### ISSUE TITLE
Readme.md instead of readme.txt

### ISSUE THREAD

**Issue by krishnavelu** [FreeRTOS/FreeRTOS#9]
Can we convert [readme.txt](https://github.com/FreeRTOS/FreeRTOS/blob/master/readme.txt) to readme.md and use [markdown](https://guides.github.com/features/mastering-markdown/) format?

**Comment by RichardBarry** [comment]
That readme file is not appropriate as a readme.md file that will display in Github.  I suggest we change readme.txt to something that describes its contents, such as "directories.txt", and then introduce a new readme.md file that contains the same info, but also a lot more such as how to clone the repo, links to the quick start guide, etc.

**Comment by cobusve** [comment]
#11  adds a readme.md

**Comment by krishnavelu** [comment]
Wow, Just 3 Hours and its Done.
thanks @cobusve
