### ISSUE TITLE
[BUG] Freertos-Cellular port of TCP_Sockets_Recv() should report TCP_SOCKETS_ERRNO_ECLOSED for remote close

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/FreeRTOS#913]
**Describe the bug**
The TCP_Sockets_Recv() uses the `prvNetworkRecvCellular` routine to handle the actual data blocking and retrieval.

The routine properly determines the remote close scenario

https://github.com/FreeRTOS/FreeRTOS/blob/c7b3124565d9591640c491d296ff2da665e5eb9a/FreeRTOS-Plus/Source/Application-Protocols/network_transport/tcp_sockets_wrapper/ports/cellular/tcp_sockets_wrapper.c#L326-L336

but when translating the `socketStatus` to `retRecvLength` return code, the handling for `CELLULAR_SOCKET_CLOSED` is missing, thus it is translated to the broadest `TCP_SOCKETS_ERRNO_ERROR` error code.

https://github.com/FreeRTOS/FreeRTOS/blob/c7b3124565d9591640c491d296ff2da665e5eb9a/FreeRTOS-Plus/Source/Application-Protocols/network_transport/tcp_sockets_wrapper/ports/cellular/tcp_sockets_wrapper.c#L348-L356

**Target**
FreeRTOS-Cellular tcp_sockets_wrapper implementation.

**Host**
All platforms

**To Reproduce**
Open socket with `TCP_Sockets_Connect()` and do blocking read with `TCP_Sockets_Recv()`, close the remote connection.

One can use `netcat -l` as the server.

**Expected behavior**
`TCP_Sockets_Recv()` should report `TCP_SOCKETS_ERRNO_ECLOSED` when remote closes the connection, interrupting the blocking read.

**Comment by chinglee-iot** [comment]
This issue is updated in #922.
