### ISSUE TITLE
[DOC] FreeRTOS-CLI documentation "Implementing a Command" page is missing

### ISSUE THREAD

**Issue by t123yh** [FreeRTOS/FreeRTOS#914]
**Describe the issue**
When clicking [the link](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_CLI/FreeRTOS_Plus_CLI_Implementing_A_Command.html), it goes to 404 page.

**Reference**
https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_CLI/FreeRTOS_Plus_Command_Line_Interface.html

**Screenshot**
![image](https://user-images.githubusercontent.com/8972552/213735028-06770f35-7794-4c30-ab45-03dd2a345cc1.png)

**Browser**
Chrome latest

**Comment by archigup** [comment]
Hi, thanks for reaching out! We're looking into this.

**Comment by n9wxu** [comment]
Tested the link and it goes to a good place.  Thank you
