### ISSUE TITLE
[DOC] I believe that the TCP/IP stack can use static allocations, contrary to a statement in the tutorial

### ISSUE THREAD

**Issue by omarandlorraine** [FreeRTOS/FreeRTOS#951]
**Describe the issue**

The page titled _Adding the TCP/IP Source Files to an RTOS Project_ contains this statement
> The application *must* be using the [heap_4 or heap_5 memory allocator](https://www.freertos.org/a00111.html).

Further reading seems to suggest that this is only the case when using `BufferAllocation_2.c`. A page titled _TCP/IP Stack Network Buffers Allocation Schemes_ explains that allocation scheme 1 uses static allocations and scheme 2 uses dynamic allocations. 

I'm also left wondering precisely why heaps 1, 2 and 3 do not satisfy the requirements of BufferAllocation_2.c. I suppose this allocation scheme benefits from free-space coalescence, but that's a guess. It is possible that the above statement was written before there was the option of using static memory allocation, and is now out of date. This could suggest that the TCP/IP stack also does not strictly require free-space coalescence.

Could I ask that the documentation around this is revised?

**Reference**
[Adding the TCP/IP Source Files to an RTOS Project](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/TCP_Networking_Tutorial_Adding_Source_Files.html)

[TCP/IP Stack Network Buffers Allocation Schemes](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/Embedded_Ethernet_Buffer_Management.html)

**Screenshot**
If applicable, please attach screenshot.

**Browser**
- Browser: Firefox
- Version: I don't know

**Comment by paulbartell** [comment]
@omarandlorraine Indeed. Dynamic allocation is currently required for FreeRTOS+TCP. Until this is addressed in the library, one alternative to a traditional heap allocator would be to use a memory-pool based allocator which can ensure that heap fragmentation does not occur.
