### ISSUE TITLE
[BUG] Out of date text file

### ISSUE THREAD

**Issue by RichardBarry** [FreeRTOS/FreeRTOS#975]
**Describe the bug**
https://github.com/FreeRTOS/FreeRTOS/blob/main/FreeRTOS-Plus/readme.txt doesn't describe the VisualStudio_StaticProjects directory.  VisualStudio_StaticProjects also needs a readme describing the directories it contains.

**Target**
None.

**Host**
None

**To Reproduce**
None

**Expected behavior**
All directories to contain information describing their contents.

**Screenshots**
NA

**Additional context**

**Comment by kar-rahul-aws** [comment]
Closing the issue, since the required readme has been updated in a [PR](https://github.com/FreeRTOS/FreeRTOS/pull/1044)and merged.
